"""replace type with kind

Revision ID: 3a71ba0fde50
Revises: f71e62dab370
Create Date: 2023-11-30 15:10:04.938978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a71ba0fde50'
down_revision = 'f71e62dab370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('user_token', sa.String(), nullable=False))
        batch_op.drop_constraint('whiskey_booze_token_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_token'], ['token'])
        batch_op.drop_column('type')
        batch_op.drop_column('booze_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whiskey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booze_token', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('whiskey_booze_token_fkey', 'user', ['booze_token'], ['token'])
        batch_op.drop_column('user_token')
        batch_op.drop_column('kind')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
